"""Add quantity and available_quantity to books

Revision ID: 9d0d03db3111
Revises: ce33b313de8a
Create Date: 2026-07-29 00:34:22.959789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0d03db3111'
down_revision: Union[str, Sequence[str], None] = 'ce33b313de8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('available_quantity', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_column('books', 'available_quantity')
    op.drop_column('books', 'quantity')
    # ### end Alembic commands ###
